### ISSUE TITLE
The facebook open graph image is cropped badly

### ISSUE THREAD

**Issue by captn3m0** [hasgeek/droidcon#50]
While sharing on facebook, the droid is cropped badly:

![image](https://cloud.githubusercontent.com/assets/584253/10880441/3b8463a2-8181-11e5-88c4-33f42044fda2.png)

**Comment by jace** [comment]
@vidya-ram can you take this up? Facebook likes images to be in rectangular aspect ratio, so you'll have to pad the image appropriately.

**Comment by vidya-ram** [comment]
Resolved in https://github.com/hasgeek/droidcon/commit/eee10099fb49ee3280c2f760ed98ff17414d56a4

**Comment by vidya-ram** [comment]
Resolved in https://github.com/hasgeek/droidcon/commit/eee10099fb49ee3280c2f760ed98ff17414d56a4
